# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CSSconf EU 2017
description: "CSSconf EU 2017, Berlin, Germany"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://2017.cssconf.eu" # the base hostname & protocol for your site
newsletter_url: "https://confirmsubscription.com/h/d/879A481DB04CB70D"
ticket_sale_url: "https://ti.to/cssconfeu/cssconfeu-2017"

# Build settings
markdown: kramdown

collections:
  speakers:
    # Represents whether to generate pages for the collection items
    output: true
  talks:
    output: false
  sponsors:
    output: false
  transcripts:
    output: true

defaults:
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: transcripts
    values:
      # Transcripts will be output as raw txt files
      layout: null

# Don’t build Gulp and Node stuff
exclude:
  - "*README.md"
  - "*.sh"
  - "package.json"
  - "node_modules/"
  - "gulpfile.js"
